#!/bin/python3
from collections import Counter

if __name__ == '__main__':
    s = input().strip()
      # Count character frequencies
    freq = Counter(s)
    
    # Sort by frequency (descending), then alphabetically
    sorted_chars = sorted(freq.items(), key=lambda x: (-x[1], x[0]))
    
    # Print top 3 characters
    for char, count in sorted_chars[:3]:
        print(char, count)
